### ISSUE TITLE
Permission denied error if $EDITOR not defined

### ISSUE THREAD

**Issue by aslakhellesoy** [tooky/retro-tools#2]
I ran `retro add` and got:

```
/Users/aslakhellesoy/git/retro-tools/src/retro-add: line 26: doc/retro/2020/05/13.md: Permission denied
```

https://github.com/tooky/retro-tools/blob/eae9b4173ef7f0ec868930008ee8bb161eb05c06/src/retro-add#L26

...tries to ececute the Markdown file if `$EDITOR` is not defined

A simple fix would be to `set -eu` at the top

**Comment by tooky** [comment]
@aslakhellesoy thanks!
