### ISSUE TITLE
Find the root of your git repo and always use that for the path

### ISSUE THREAD

**Issue by mattwynne** [tooky/retro-tools#3]
We accidentally managed to run `retro add` in a sub-folder, and committed a new `doc` directory in there without noticing.

It was fine, we tidied it up.

But today I just noticed that `adr-tool` can figure this out. If you run it in a sub-folder, it still knows to create the file off the root directory. Neat.

**Comment by tooky** [comment]
Thanks - this is a nice feature.

I don't think it needs to depend on git though. Searching up for a retro dir should be sufficient.
